# Generated by Django 4.0 on 2022-01-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('surname', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('year_of_production', models.DateField()),
                ('engine_power', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('mass_kg', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=666.69, max_digits=8)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lend', models.DateField()),
                ('date_return', models.DateField()),
                ('final_price', models.DecimalField(decimal_places=2, default=123.45, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YachtsApp.customer')),
                ('yachts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YachtsApp.yacht')),
            ],
        ),
    ]
