# Generated by Django 4.0 on 2022-01-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YachtsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='id_yachts',
            new_name='yachts',
        ),
        migrations.RenameField(
            model_name='yacht',
            old_name='name_yacht',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='yacht',
            old_name='type_yacht',
            new_name='type',
        ),
    ]
