# Generated by Django 4.0 on 2022-01-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YachtsApp', '0002_rename_id_customer_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='price',
            field=models.DecimalField(decimal_places=2, default=666.69, max_digits=8),
        ),
    ]
