# Generated by Django 4.0 on 2022-01-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YachtsApp', '0004_yacht_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=123.45, max_digits=10),
        ),
    ]
